baseURL = 'http://sir-thomas.github.io/'
languageCode = 'en-us'
title = 'My Blog'
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    github = "https://github.com/Sir-Thomas"
    twitter = "https://twitter.com/XXX"
    email = "tommy@sirthomas.xyz"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"